name: NPM Upgrade

on:
  schedule:
    - cron: "0 6 * * 1" # Every Monday at 6:00 AM
  workflow_dispatch:

jobs:
  npm-upgrade:
    uses: devopsplaybook-io/common-utils/.github/workflows/reusable-npm-upgrade.yml@main
    permissions:
      contents: write
      pull-requests: write
    with:
      npm_services: '["notifications-proxy", "notifications-server", "notifications-web"]'
